### PR TITLE
Fixing slight bug

### LINKED ISSUE #54: record creation attempted for non-defined sequencer tables
If SEQ2 isn't defined for the panda (in the web gui) then in `IocRecordFactory::_make_table` we'll have an `_all_values_dict["SEQ2:TABLE"]` of `[]`, and `SEQ2:TABLE:TRIGGER` will be 0 instead of a string enum value. This causes a failure when building the ioc.

### PR DESCRIPTION
**Pull request by evalott100**
Closes #54 

There is a slight bug in the current code, sometimes the enum values will come in as strings and sometimes they will come in as integers (corresponding to the index in the `field_details.labels`).

This adjusts the code to work for either case.

### CODE REVIEW

**Comment by AlexanderWells-diamond** [comment]
When does this bug occur? From the looks of it, this code is only called during construction of a table after receiving all the data from PandA. And PandA will only ever send data in one format (the string? I forget). So I'd like to understand exactly where/when the different form of data is arriving in this function, to ensure we're fixing the bug in the right place.

**Comment by AlexanderWells-diamond** [comment]
I can't say I understand this. This code has previously been used to create an IOC from the PandA in the lab. 

It looks like this code changed in cb6b6e9abd584edaaa2d56c3682ed36ab86956e1, so I would suspect that that commit is where the difference has come from. I haven't looked deeply into it, but I suspect that commit changes `initial_value` to be a string rather than an integer by this point.

Ultimately, this code should only be receiving one type of data, not two, so handling two is incorrect.

**Comment by evalott100** [comment]
Putting it back to what it was:
``` python
                scalar_record = builder.mbbIn(
                    scalar_record_name,
                    *field_details.labels,
                    initial_value=initial_value,
                    DESC=scalar_record_desc,
                )
```
we get an error on the following field
```
FIELD NAME TRIGGER
INIIAL VALUE Immediate
INIIAL VALUE TYPE <class 'str'>
FIELD LABELS ['Immediate', 'BITA=0', 'BITA=1', 'BITB=0', 'BITB=1', 'BITC=0', 'BITC=1', 'POSA>=POSITION', 'POSA<=POSITION', 'POSB>=POSITION', 'POSB<=POSITION', 'POSC>=POSITION', 'POSC<=POSITION']
```

If we look up on index without checking for string initial value:
``` python
                    initial_value=field_details.labels.index(initial_value),
```

 we get an error for
```
FIELD NAME TRIGGER
INIIAL VALUE 0
INIIAL VALUE TYPE <class 'int'>
FIELD LABELS ['Immediate', 'BITA=0', 'BITA=1', 'BITB=0', 'BITB=1', 'BITC=0', 'BITC=1', 'POSA>=POSITION', 'POSA<=POSITION', 'POSB>=POSITION', 'POSB<=POSITION', 'POSC>=POSITION', 'POSC<=POSITION']
```

This is during the `ioc._make_table` of `SEQ2:TABLE`, `SEQ1:TABLE` works perfectly fine the old way (it sends across a str). I think this is because the values aren't actually defined for the panda in the web controller?

**Comment by AlexanderWells-diamond** [comment]
Looking at the web UI for SEQ2, it looks like there are no rows at all. So it sounds like the issue here is attempting to create a defined record for a row that doesn't exist. I don't know if I ever tested this.

**Comment by evalott100** [comment]
Yep I suspect that's it too: `SEQ2:TABLE` has the enum values for trigger defined, but it sends across 0 since the field doesn't exist at all.

**Comment by AlexanderWells-diamond** [comment]
To note what was discussed offline: We have to create the PVs, otherwise we will be unable to add rows to those tables after the IOC is initialised. There is perhaps a bug in pandablocks-client regarding returning values for tables with no rows - if there is no row our code receives an integer, whereas if there is a row we receive a string. This mismatch should probably be resolved in that repository, rather than working around it here.

We should also add tests regarding adding/removing rows when there are no rows initially defined for a table.

**Comment by evalott100** [comment]
After talking about it more we agree that the default values should remain on the ioc side: pandalocks_client `words_to_table` shouldn't assume default values `0` but accept that values are `None`.

The ioc will continue to assume default values of `0` for undefined tables, but use `field_labels[0]` for the enum values.

### TESTING

For the test panda where SEQ1 exists and SEQ2 doesn't we have:

Default values continue to be `0`:
```
caget PANDA:SEQ1:TABLE:OUTB1 -> PANDA:SEQ1:TABLE:OUTB1 16384 0 0 0 0 0 0 ...
caget PANDA:SEQ2:TABLE:OUTB1 -> PANDA:SEQ2:TABLE:OUTB1 16384 0 0 0 0 0 0 ...
```

Enum values default to the `0`th label:
```
caget PANDA:SEQ1:TABLE:TRIGGER -> 16384 Immediate
caget PANDA:SEQ2:TABLE:TRIGGER -> 16384 Immediate
```

The panda sends across no data, `field_data[field_name] == []` here:

https://github.com/PandABlocks/PandABlocks-ioc/blob/35360f4e29a32bf7cdc54e9d1d210c52b3d3f729/src/pandablocks_ioc/_tables.py#L357

**Comment by evalott100** [comment]
@AlexanderWells-diamond

I've moved the test to `update_table` on a table previously `[]` to a different branch. I'm not convinced the way labels are handled in that function is correct (at least with a newer method of handling enums). In the interest of getting a fix for this out quickly I suggest we merge this first.

**Pull request closed without merging**
