### PR TITLE
Changed test to use lower case names consistent with PVA

### LINKED ISSUE #13: Fix failing unit test
In the test `tests/test_pvaccess.py::test_table_column_info`, the table received from the ioc has the lower case key "repeats" rather than "REPEATS" as is expected.

### PR DESCRIPTION
**Pull request by evalott100**
Closes #13

### CODE REVIEW

**Comment by AlexanderWells-diamond** [comment]
Is this a correct understanding of the situation?

We create a series of records for the tables, and we pass in the name of each column as an extra bit of info. As PandA returns that name in capitals, we pass it in like that, but then PVI is internally converting it to lower case? Is that an expected behaviour? It seems like an odd bit of unnecessary work that it's doing.

**Comment by evalott100** [comment]
> Is this a correct understanding of the situation?
> 
> We create a series of records for the tables, and we pass in the name of each column as an extra bit of info. As PandA returns that name in capitals, we pass it in like that, but then PVI is internally converting it to lower case? Is that an expected behaviour? It seems like an odd bit of unnecessary work that it's doing.

@coretl mentioned this maybe he can weight in? I remember hearing that names will be capitalised and made lowercase at different points in the I22 run we're planning

**Comment by coretl** [comment]
That is correct, we need the names in the PVI structure, and the names in the PVA table structure to be lowercase, as we tie python attribute names to this in Ophyd...

**Comment by AlexanderWells-diamond** [comment]
Sorry, I don't quite get it: We create the PVI name tags, and we're creating them in uppercase? But then when we receive them through pvget we see lowercase strings? I don't see how Ophyd is related to what I believe is happening entirely inside this codebase?

**Comment by coretl** [comment]
In this line I make the PVA table column lowercase:
https://github.com/PandABlocks/PandABlocks-ioc/blob/a8586b9fde836a8a8eceda770c935f39af57f98c/src/pandablocks_ioc/_tables.py#L317

This makes the same name to the tests.

In #18 I also make the PVI structure name lowercase, so that's not actually part of this PR...

**Review by AlexanderWells-diamond — APPROVED** [review]

**Pull request merged**
